[package]
name = "turbojpeg"
version = "0.0.1"
edition = "2018"

[dependencies]
libc = "^0.2"
thiserror = "^1.0"
turbojpeg-sys = {path = "turbojpeg-sys", version = "^0.0.1"}

[dev-dependencies]
anyhow = {version = "1.0"}
image = {version = "0.23", features = ["jpeg", "png", "bmp", "farbfeld", "pnm"]}
clap = "2.33"

[features]
bindgen = ["turbojpeg-sys/bindgen"]
pkg-config = ["turbojpeg-sys/pkg-config"]
